services:
  redis:
    image: redis
    container_name: redis2
    ports:
      - "6380:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market-db
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: